@ShareAPI_HostAddress = https://localhost:7288

POST {{ShareAPI_HostAddress}}/sharing/
Accept: application/json

###

GET {{ShareAPI_HostAddress}}/sharing/string

###

DELETE {{ShareAPI_HostAddress}}/sharing/string

###